#!/bin/sh
#PBS -N test_1
#PBS -q serial 
#PBS -P CSCI1166
#PBS -l select=1:ncpus=1
#PBS -l walltime=00:15:00
#PBS -o /mnt/lustre/users/iferreira/demo/logs/standard.out
#PBS -e /mnt/lustre/users/iferreira/demo/logs/error.out
#PBS -m abe -M u25755422@tuks.co.za
ulimit -s unlimited

echo 'Starting experiment'

cd /mnt/lustre/users/iferreira/demo
module load chpc/python/anaconda/3-2021.11
pwd -P
source /mnt/lustre/users/iferreira/myenv/bin/activate

pip list

python /mnt/lustre/users/iferreira/demo/test.py
